### ISSUE TITLE
Gdata migration ?

### ISSUE THREAD

**Issue by sfonteneau** [baboons/samba4-gaps#8]
With statements from google : 
http://googleappsupdates.blogspot.fr/2015/03/final-reminder-deprecated-google-apps.html

Are we affected ?

Should update gdata -python- client?
https://github.com/google/gdata-python-client

That Works with gaps ?

Thank you for your help

**Comment by baboons** [comment]
We are affected. I'm working on implementing the new Admin SDK Directory API. Hopefully I will be done before 20th of April.

**Comment by sfonteneau** [comment]
Great, thank you for your help.

**Comment by baboons** [comment]
Updated. Running this version in my production system currently and works fine. However it requires a bit work to get started since you need to create a project in the Google Developer Console.

Good luck!

**Comment by sfonteneau** [comment]
Great it works !

Thank you for your help !
